### ISSUE TITLE
One of Install gvisor-containerd-shim steps is not correct.

### ISSUE THREAD

**Issue by Apokleos** [google/gvisor-containerd-shim#18]
When I follows the official doc[https://github.com/google/gvisor-containerd-shim/blob/master/docs/runtime-handler-quickstart.md] and try to install gvisor-containerd-shim, somthing goes wrong!
[root@localhost runsc]# LATEST_RELEASE=$(wget -qO - https://api.github.com/repos/google/gvisor-containerd-shim/releases | grep -oP '(?<="browser_download_url": ")https://[^"]*' | head -1)
[root@localhost runsc]# echo $LATEST_RELEASE
https://github.com/google/gvisor-containerd-shim/releases/download/v0.0.1/containerd-shim-runsc-v1.linux-amd64
[root@localhost runsc]# wget -O gvisor-containerd-shim
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

The step " wget -O gvisor-containerd-shim" should be "wget -O gvisor-containerd-shim $LATEST_RELEASE"
I have verified that "wget -O gvisor-containerd-shim $LATEST_RELEASE" is OK.

**Comment by ianlewis** [comment]
Yeah, looks like that step got missed somehow

**Comment by Apokleos** [comment]
And the same kind bug in Untrusted Workload Quickstart[https://github.com/google/gvisor-containerd-shim/blob/master/docs/untrusted-workload-quickstart.md]

**Comment by ianlewis** [comment]
Getting errors when testing a fix. Maybe there is something wrong with the latest release? need to investigate. Hopefully sometime later this week.
https://travis-ci.org/ianlewis/gvisor-containerd-shim/builds/499117397
