### ISSUE TITLE
RuntimeHandler "runsc" not supported Kuberentes

### ISSUE THREAD

**Issue by alexcpn** [google/gvisor-containerd-shim#46]
Installed gvisor/runsc, containerd, gvisor-containerd-shim and containerd-shim-runsc-v1 in all nodes of kubernetes cluster.

In all nodes I am able to start the nginx container in the sandbox as is documented in [1] with runsc.

Created the Runtimeclass gvisor using runsc as per [1]description and created a  Pod with the gVisor Runtime Class [1] 

However, the pod is not able to start; This is the event - RuntimeHandler "runsc" not supported

`3m47s       Warning   FailedCreatePodSandBox   pod/nginx-gvisor                                 Failed to create pod sandbox: rpc error: code = Unknown desc = RuntimeHandler "runsc" not supported
`
Kubernetes version below;  Cluster installed via kubeadm.

`
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
`

[1] https://github.com/google/gvisor-containerd-shim/blob/master/docs/runtime-handler-shim-v2-quickstart.md

**Comment by jonbudd** [comment]
@alexcpn Just to confirm, did you [update your containerd config.toml](https://github.com/google/gvisor-containerd-shim/blob/master/docs/runtime-handler-shim-v2-quickstart.md#configure-containerd) to include the entry for runsc, and restart containerd? At a glance, it seems like this file may not properly be configured, since [that file is containerd's source of truth](https://kubernetes.io/docs/concepts/containers/runtime-class/#a-class-glossary-tooltip-href-https-containerd-io-docs-target-blank-containerd-span-class-tooltip-text-a-container-runtime-with-an-emphasis-on-simplicity-robustness-and-portability-span) for what is considered a valid runtimehandler.

**Comment by ianlewis** [comment]
We also had a similar issue come up in the comments on #32. Though I don't think there was resolution.

If you were able to create an nginx sandbox using `crictl` then it should work. Please verify that the container is running in a sandbox:

    sudo crictl exec ${CONTAINER_ID} dmesg | grep -i gvisor

Also, please verify that your Kubernetes cluster is using the containerd that you've set up to use runsc. I'm not sure off hand what kubeadm uses by default but you may need to pass it a couple parameters like `--container-runtime=remote` and `--container-runtime-endpoint=unix:///var/run/containerd/containerd.sock` in order for it to use your containerd.

See: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#providing-instance-specific-configuration-details

**Comment by ianlewis** [comment]
I looked around a bit more and it looks like if the docker.sock exists then Docker takes precedence.
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-runtime

The container runtime options I wrote above should fix it but just to be sure, could you check if Docker is installed? specifically if the `/var/run/docker.sock` file exists?

**Comment by ianlewis** [comment]
My bad, those options above are the options for the kubelet. For kubadm you want to use `--cni-socket /var/run/containerd/containerd.sock`

**Comment by alexcpn** [comment]
> @alexcpn Just to confirm, did you [update your containerd config.toml](https://github.com/google/gvisor-containerd-shim/blob/master/docs/runtime-handler-shim-v2-quickstart.md#configure-containerd) to include the entry for runsc, and restart containerd? At a glance, it seems like this file may not properly be configured, since [that file is containerd's source of truth](https://kubernetes.io/docs/concepts/containers/runtime-class/#a-class-glossary-tooltip-href-https-containerd-io-docs-target-blank-containerd-span-class-tooltip-text-a-container-runtime-with-an-emphasis-on-simplicity-robustness-and-portability-span) for what is considered a valid runtimehandler.

Yes this is done; have followed all documentation and also tested via circtl; 

```
[root@azuretest-2 ~]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─0-containerd.conf
        /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Thu 2020-01-30 14:42:37 IST; 2min 12s ago
     Docs: https://kubernetes.io/docs/
 Main PID: 3058 (kubelet)
   CGroup: /system.slice/kubelet.service
           └─3058 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib...



[root@azuretest-2 ~]# cat  /proc/3058/net/unix 
Num       RefCount Protocol Flags    Type St Inode Path
ffff8801f5d19000: 00000002 00000000 00010000 0001 01 19515 private/verify
ffff8801f5d1a800: 00000002 00000000 00010000 0001 01 19521 private/proxymap
ffff8801f5d1b400: 00000002 00000000 00010000 0001 01 19524 private/proxywrite
ffff8801f5d1c000: 00000002 00000000 00010000 0001 01 19527 private/smtp
ffff8801f5d1cc00: 00000002 00000000 00010000 0001 01 19530 private/relay
ffff8800bb856c00: 00000002 00000000 00010000 0001 01 31748 /var/run/docker/libcontainerd/docker-containerd.sock
```

**Comment by alexcpn** [comment]
> My bad, those options above are the options for the kubelet. For kubadm you want to use `--cni-socket /var/run/containerd/containerd.sock`

My use case was to enable it in an already exsiting Kubernetes cluster. Are you suggesting that I need to create a cluster afresh , Kubeadm --init ...

**Comment by ianlewis** [comment]
Yeah, the kubelet is probably connecting to docker via docker's socket file.

Assuming you installed kubeadm via the apt or rpm package, try editing the `/var/lib/kubelet/kubeadm-flags.env` file. That is where kubeadm adds it's own options for the kubelet. I'm guessing you don't have the `--container-runtime` or `--container-runtime-endpoint` flags in there. Add those so that it looks something like the following and then restart the kubelet.
```
sudo cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS="--container-runtime=remote --container-runtime-endpoint=/var/run/containerd/containerd.sock --resolv-conf=/run/systemd/resolve/resolv.conf"
```

After that I think it should work.

**Comment by ianlewis** [comment]
@alexcpn  Oh, and before you do that I recommend you make sure there aren't any running workloads on the node. So drain it using `kubectl drain` and make sure no pods are running on it via statefulsets etc.

Otherwise I think Kubernetes will get confused about the containers running on the node.

**Comment by alexcpn** [comment]
Working ! Thanks for the help

There was an error in my centos box first in kubelet start 

` Warning   FailedCreatePodSandBox     pod/nginx-gvisor                                  Failed to create pod sandbox: open /run/systemd/resolve/resolv.conf: no such file or directory
`
Found a related [bug ?](https://github.com/ivanfioravanti/kubernetes-the-hard-way-on-azure/issues/30)  ; I added a symlink to /etc/resolv.conf and then kubelet  started with containerd

Deployed the sample nginx-gvisor  from the [quickstart](https://github.com/google/gvisor-containerd-shim/blob/master/docs/runtime-handler-shim-v2-quickstart.md)  and found the cotainerid and checked as per [runtimehandler shim v2 quickstart guide](https://github.com/google/gvisor-containerd-shim/blob/master/docs/runtime-handler-shim-v2-quickstart.md#configure-containerd)
and it seems to run in runsc

> [root@azuretest-2 ~]# CONTAINER_ID=a56c197fd2a6fcba9fc02d75f3552a81b4ed9af01b575ab7e2a8fbbbb6b12e85
> [root@azuretest-2 ~]# sudo crictl exec ${CONTAINER_ID} dmesg | grep -i gvisor
> [    0.000000] Starting gVisor...
> [root@azuretest-2 ~]# sudo crictl exec ${CONTAINER_ID} dmesg 
> [    0.000000] Starting gVisor...
> [    0.490852] Letting the watchdogs out...
> [    0.601648] Constructing home...
> [    0.706648] Searching for socket adapter...
> [    0.935407] Feeding the init monster...
> [    1.072809] Creating process schedule...
> [    1.115258] Synthesizing system calls...
> [    1.474947] Daemonizing children...
> [    1.551481] Moving files to filing cabinet...
> [    1.631282] Mounting deweydecimalfs...
> [    2.120791] Reading process obituaries...
> [    2.613084] Ready!
 
I guess if the document can be updated on certain steps to enable containerd with kubelet then it will be more easier to follow

**Comment by ianlewis** [comment]
oh, right. the `--resolv-conf=/run/systemd/resolve/resolv.conf` option in `/var/lib/kubelet/kubeadm-flags.env` that I wrote above wasn't important. It was just what I had when I was testing. You could leave it as whatever it was set to before.

I'll add some info to the doc later for folks who are using kubeadm. I think that it's pretty common that folks will install a cluster using kubeadm with Docker installed and that will make it difficult to use RuntimeClass and CRI runtime handlers.

Anyway, glad that you got it working!
